version: '3.7'
services:
  php:
    image: bscheshir/php:7.4.3-fpm-alpine-4yii2
    restart: always
    volumes:
      - ./php-data:/var/www/html #php-data
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  nginx:
    image: nginx:1.17.8-alpine
    restart: always
#    ports: # use nginx-proxy in same network (see ./docs/nginx-proxy.md)
    depends_on:
      - php
    volumes:
      - ./php-data:/var/www/html #php-data
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
    networks:
      default:
      nginx-proxy:
        aliases:
          - links.bscheshir.ru.nginx
    environment:
      TZ: Europe/Moscow
  db:
    image: mysql:8.0.19
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password' # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2basic
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2basic
      MYSQL_PASSWORD: yii2basic
networks:
  nginx-proxy:
    external: true # docker network create nginx-proxy
